### ISSUE TITLE
Stop using latest tag for betas/dev/rc version

### ISSUE THREAD

**Issue by reloxx13** [OctoPrint/docker#12]
Heya,

pls dont use the docker latest tag for dev versions.

add a second tag like dev/beta/deveoper which points to beta versions and update latest tag only if its a stable release.

the easiest way would be to use github releases which triggers travis.
if "rc" is in release name, update dev tag
else update latest tag.

**Comment by LongLiveCHIEF** [comment]
Agreed. moving forward, latest will point to the latest stable release of Octoprint. So for now, that would mean `latest` and `1.4.0` tags would point to the same digests.

I'll be making this update later today.

**Comment by LongLiveCHIEF** [comment]
#35 switched the `latest` tag to be equal to the latest stable release, but I will need to validate that my version.sh script will return the latest stable, and not any RC's that are released.

**Comment by gaetancollaud** [comment]
Since #35 is merge I will close this one.
