### ISSUE TITLE
Not an issue: just suggestions

### ISSUE THREAD

**Issue by walchko** [OctoPrint/docker#15]
I just made my own version of this ... you might be able to use some ideas from my [Dockerfile](https://github.com/MomsFriendlyRobotCompany/docker-octoprint/blob/master/Dockerfile) or my [helper script](https://github.com/MomsFriendlyRobotCompany/docker-octoprint/blob/master/sdock.sh).

**Comment by gaetancollaud** [comment]
@badsmoke @LongLiveCHIEF FYI

I'm closing this
