### ISSUE TITLE
Update docker image to at least 1.3.11

### ISSUE THREAD

**Issue by ModischFabrications** [OctoPrint/docker#16]
The official releases are at version [1.3.12rc3](https://github.com/foosel/OctoPrint/releases), the current docker version (probably) is 1.3.9, which is >10 months old. Release candidates might be too much work to keep up with but at least the latest stable version should be available as a docker image. If work is done on that new images should probably feature more precise tags as noted in #12.

I wasn't able to test further because this image is not ARM-ready as noted in #6, this completely disqualifies this image for me as I am using a Raspberry Pi, which seemed like it's the recommended platform, at least for the installed builds.

I switched to https://hub.docker.com/r/nunofgs/octoprint for now but will happily switch to an official build once it is usable.

**Comment by LongLiveCHIEF** [comment]
Closed with #19 

We're now publishing both python 2 and python 3 versions of from both master and latest stable release (1.4.0 at the time of this comment).

Check them out on hub.docker.com/r/octoprint/octoprint
