### ISSUE TITLE
Permission denied for home.config.yaml

### ISSUE THREAD

**Issue by scubieman** [OctoPrint/docker#23]
Not sure how to fix this error
Trying to follow this video also   https://www.youtube.com/watch?v=Y-2o0gyGB4c

> Starting octoprint-docker_octoprint_1 ... done
> Attaching to octoprint-docker_octoprint_1
> octoprint_1  | 2020-03-26 18:47:51,628 - octoprint.settings - ERROR - Error while saving config.yaml!
> octoprint_1  | Traceback (most recent call last):
> octoprint_1  |   File "/opt/venv/lib/python2.7/site-packages/OctoPrint-1.4.0-py2.7.egg/octoprint/settings.py", line 1388, in save
> octoprint_1  |     self._dirty = False
> octoprint_1  |   File "/usr/local/lib/python2.7/contextlib.py", line 24, in __exit__
> octoprint_1  |     self.gen.next()
> octoprint_1  |   File "/opt/venv/lib/python2.7/site-packages/OctoPrint-1.4.0-py2.7.egg/octoprint/util/__init__.py", line 1105, in atomic_write
> octoprint_1  |     shutil.move(temp_config.name, filename)
> octoprint_1  |   File "/usr/local/lib/python2.7/shutil.py", line 325, in move
> octoprint_1  |     copy2(src, real_dst)
> octoprint_1  |   File "/usr/local/lib/python2.7/shutil.py", line 153, in copy2
> octoprint_1  |     copyfile(src, dst)
> octoprint_1  |   File "/usr/local/lib/python2.7/shutil.py", line 97, in copyfile
> octoprint_1  |     with open(dst, 'wb') as fdst:
> octoprint_1  | IOError: [Errno 13] Permission denied: u'/home/octoprint/.octoprint/config.yaml'
> octoprint_1  | 2020-03-26 18:47:51,629 - octoprint.startup - CRITICAL - Could not initialize settings manager: [Errno 13] Permission denied: u'/home/octoprint/.octoprint/config.yaml'
> octoprint_1  | 2020-03-26 18:47:51,629 - octoprint.startup - CRITICAL - There was a fatal error starting up OctoPrint.
> octoprint_1  | Could not initialize settings manager: [Errno 13] Permission denied: u'/home/octoprint/.octoprint/config.yaml'
> octoprint_1  | There was a fatal error starting up OctoPrint.
> octoprint-docker_octoprint_1 exited with code 0

Here is my docker-compose.yaml                                        

> version: '3.7'
> 
> volumes:
>   octoprint-docker:
> 
> services:
>   octoprint:
>     image: octoprint/octoprint
>     ports:
>       - 5001:5001
>     # devices:
>     #  - /dev/ttyACM0:/dev/ttyACM0
>     volumes:
>      - octoprint-docker:/home/octoprint/.octoprint

**Comment by LongLiveCHIEF** [comment]
Watch the whole video :smiley: ... specifically at [2:00](https://youtu.be/Y-2o0gyGB4c?t=120) :wink:

**Comment by LongLiveCHIEF** [comment]
You'll also want to make sure the port inside the container is `5000`.

**Comment by scubieman** [comment]
Couple things, I tried to change to same as the 2:00 mark.

Also I tried port 5000. Just running two different dockers of unraid Thats why i have 5001.

Also my yaml matches the 2 minute mark

**Comment by LongLiveCHIEF** [comment]
Would you be willing to reach out to me on the #octoprint channel on freenode, or join my HackerHappyHour discord server and live-debug this one with me? This discord invite link will take you directly to the raspberry-pi channel on that server: https://discord.gg/hGwvAPp.

The only thing wrong I see with your yaml pasted above is formatting, but that could just be a result of using a blockquote instead of code insertion backticks.

when you type `docker-compose config` do you get an error, or does it spit out a copy of your resolved configuration?

Also, when you type `groups` can you confirm that the following groups all show up `docker` `plugdev`, `dialout`, `tty`

**Comment by LongLiveCHIEF** [comment]
Looks like I forgot to add back in user membership to `tty` and `dialout` groups for access to `/dev/ttyUSB*` and `/dev/ttyACM*`.
