### ISSUE TITLE
Incorrect folder mount in README

### ISSUE THREAD

**Issue by lachyc** [OctoPrint/docker#43]
README states ` -v ./config:/home/octoprint/.octoprint` as a required mount but the Dockerfile lists `VOLUME /home/octoprint` instead. Mounting  /home/octoprint as per the Dockerfile seems to cause execution permission errors on my system. Changing to `VOLUME /home/octoprint/.octoprint` in the Dockerfile fixes these issues.

[Pull Request](https://github.com/OctoPrint/docker/pull/42)

**Comment by LongLiveCHIEF** [comment]
The README needs to be updated.  Can you use `-v ./config:/home/octoprint` to mount instead?

I updated the docker-compose.yml file, but haven't yet made it around to updating the README because there are a LOT of changes, and we're not yet at the "stable" release milestone for this image.

**Comment by LongLiveCHIEF** [comment]
closed #48
