### ISSUE TITLE
docker hub docs are incorrect

### ISSUE THREAD

**Issue by cshotton** [OctoPrint/docker#49]
The "Without docker compose" section at [https://hub.docker.com/r/octoprint/octoprint/](https://hub.docker.com/r/octoprint/octoprint/) is incorrect.
Specifically the "-v" parameter before the --device flag causes an error. It either needs to be removed, or the instructions to create an octoprint volume need to be added and the volume referenced after the -v.

**Comment by gaetancollaud** [comment]
Hi @cshotton 

Thanks for your contribution ! I'ts fixed. I removed the `-v`.
