### ISSUE TITLE
failes ffmpeg url

### ISSUE THREAD

**Issue by xpix** [OctoPrint/docker#8]
Please check:

```
--2018-05-17 09:43:27--  https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz
Resolving johnvansickle.com (johnvansickle.com)... 162.222.226.121
Connecting to johnvansickle.com (johnvansickle.com)|162.222.226.121|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-05-17 09:43:29 ERROR 404: Not Found.

```

replace in Dockerfile with:
`https://ffmpeg.org/releases/ffmpeg-4.0.tar.bz2`

**Comment by Cthanatos** [comment]
Well, until it gets fixed - here's what I did. (use at your own risk, as SSL certs are important for a reason)

- Get into the shell of your docker as root user with
`docker exec -u 0 -it organizr /bin/bash`

 - change to tmp directory
 `cd /tmp/`

- Use wget to get the file, but you have to ignore the certificate issues ( You'll get warnings, but it still downloads)
` wget --no-check-certificate -O  ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-32bit-static.tar.xz`

 - Make the directory before unzipping the tar
` mkdir -p /opt/ffmpeg`

 - Untar to the right location
`tar xvf ffmpeg.tar.xz -C /opt/ffmpeg --strip-components=1`

 - Remove ffmpeg download file
`rm -Rf /tmp/*`

 - Set right location in webUI when setting up for ffmpeg
`/opt/ffmpeg/ffmpeg`

**Comment by fionnb** [comment]
The new, correct URL is:
https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-armel-static.tar.xz

It is just a matter of replacing it in the Dockerfile.
